# Generated by Django 4.1.7 on 2023-03-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_profile_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='corp_email',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
