# Generated by Django 4.1.7 on 2023-03-01 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_remove_profile_length_of_last_session_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='TaskTracker',
        ),
    ]
