# Generated by Django 4.1.7 on 2023-03-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_card_tasktracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='corp_email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
    ]
