# Generated by Django 4.1.7 on 2023-03-02 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profile_corp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktracker',
            name='workplace_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.workplace'),
        ),
    ]
