# Generated by Django 4.1.7 on 2023-03-02 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_tasktracker_workplace_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreport',
            name='login',
        ),
        migrations.RemoveField(
            model_name='tasktracker',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='workplace',
            name='owner',
        ),
        migrations.AddField(
            model_name='bugreport',
            name='login',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktracker',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workplace',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
